### ISSUE TITLE
Converting trace to json

### ISSUE THREAD

**Issue by dubik** [01org/IntelSEAPI#2]
Is this suppose to do the conversion?
python &lt;InstalDir&gt;IntelSEAPI\bin\sea_runtool.py -o &lt;target&gt; -f gt -i &lt;source folder&gt;

It just exits. I tried on my own trace and on the output from test app - same result. I compiled latest master myself on osx.

**Comment by araud** [comment]
Hello, Sergiy!

Thank you for your feedback!

Could you please provide more details on your case?

For me python sea_runtool.py -o -f gt -i
Ends with error:

`
usage: sea_runtool.py [-h] -f
                      [{mfc,mfp,gt,gv,btf,dgml,qt,xcode} [{mfc,mfp,gt,gv,btf,dgml,qt,xcode} ...]]
                      [-o OUTPUT] [-b BINDIR] [-i INPUT]
                      [-t [TRACE [TRACE ...]]] [-d DIR] [-v]
                      [-c [CUTS [CUTS ...]]] [-s SYNC] [-m] [-r RING]
                      [--time_shift TIME_SHIFT] [-l LIMIT] [--ssh SSH]
                      [-p PASSWORD] [--dry] [--stacks] [--min_dur MIN_DUR]
                      [--sampling SAMPLING] [--distinct]
                      [--memory {total,detailed}] [--debug] [--profile]
                      [--collector {dtrace,ftrace,default}] [--strip_aliens]
                      [--remove_args] [--rem REM]
sea_runtool.py: error: argument -o/--output: expected one argument
`

Here is the usage example:

`
python ./buildall.py
python ./runtool/sea_runtool.py -b ./build_darwin/bin -o /tmp/test -f gt ! ./build_darwin/bin/TestIntelSEAPI
`

It builds and runs collection on the Test application.

**Comment by dubik** [comment]
ah, sorry, looks like github ate &lt; and &gt;.
I put paths to -o and to -i. But sea_runtool.py doesn't convert anything. I have a trace, I would like to convert it to json. As I understand -o /tmp/trace -i /tmp/readytrace-28340 -f gt should be enough. I also couldn't convert to json existing trace produced by test run from project's root directory.

**Comment by araud** [comment]
Could you please provide me with the full console output with the actions you do and the results you get?

**Comment by dubik** [comment]
I compiled the library, on OSX sierra. Modified test_osx.sh to do not generate google trace.
`python ./runtool/sea_runtool.py -b ./build_darwin/bin -o ./build_darwin/Test -f qt --stacks ! ./build_darwin/bin/TestIntelSEAPI`

(for some reason I had to have something in `-f`, which is weird because I'm ok with having plain trace output and don't need any conversion at this stage)

```
# bob in ~/Projects/general/IntelSEAPI on git:master ● → ./test_osx.sh
Cut # <None>
Translation: pid-6535 (548.9 KB) [ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ]
result: ['/Users/bob/Projects/general/IntelSEAPI/build_darwin/Test.pid-6535.qtd']
Time Elapsed: 0:00:05
```

I have vanila trace in correct directory:
```
# bob in ~/Projects/general/IntelSEAPI on git:master ● → ls -la build_darwin/Test
total 0
drwxr-xr-x   3 bob  staff   102 Dec 16 10:08 .
drwxr-xr-x  11 bob  staff   374 Dec 16 10:08 ..
drwxr-xr-x  40 bob  staff  1360 Dec 16 10:08 pid-6535
```

Now I want to convert it to google trace json format.
I try this:
```
# bob in ~/Projects/general/IntelSEAPI on git:master ● → python ./runtool/sea_runtool.py -o ./build_darwin/googletrace -i ./build_darwin/Test -f gt
result: []
Time Elapsed: 0:00:00
```

Nothing, then I try more specific:
```
# bob in ~/Projects/general/IntelSEAPI on git:master ● → python ./runtool/sea_runtool.py -o ./build_darwin/googletrace -i ./build_darwin/Test/pid-6535 -f gt
result: []
Time Elapsed: 0:00:00
```

I would expect an error message. I also tried few other combos, like `-o ./build_darwin/pid` and `-o ./build_darwin/pid-6535` and just `-o ./build_darwin/` but output was same and nothing was created.

**Comment by araud** [comment]
Yes, now I understand and can reproduce. Please use it without -o option for now.
The output will be beside the input.
Thank you, Sergiy, for careful bug reporting! I appreciate it.

**Comment by dubik** [comment]
Yep, omitting `-o` helped, thanks, but also I had to specify directory where trace was, not the `pid-123123`, i think this is not what documentation specifies.
