### ISSUE TITLE
Compilation does not support the MUSL c library

### ISSUE THREAD

**Issue by raphaelcohn** [01org/IntelSEAPI#26]
memory.cpp assumes that the C library on Linux always has execinfo.h present and a specific malloc implementation, both of which are actually details on the GNU libc.

As a result, it does not compile with the musl c library, making it useless for many embedded systems, impossible to use on Alpine Linux (the most popular Docket Linux currently), create fully static c binaries, etc...

**Comment by araud** [comment]
As I don't have access to embedded system environments, would be great if you could contribute this support!

**Comment by raphaelcohn** [comment]
Musl isn't an embedded C library...
