### ISSUE TITLE
Does not cleanly cross-compile

### ISSUE THREAD

**Issue by raphaelcohn** [01org/IntelSEAPI#27]
This is because all of the CMakeLists.txt files use the variables WIN32, APPLE, ANDROID (or in one place, ANDROID_NDK) and their NOT forms.

Simply replacing these with the CMAKE syntax `if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")` and the like fixes these.

**Comment by araud** [comment]
please submit the fix?

**Comment by raphaelcohn** [comment]
Why?

**Comment by raphaelcohn** [comment]
Probably not right now, but a forked copy to support a Rust wrapper I've tried to write is here:-

https://github.com/intel/IntelSEAPI/compare/master...raphaelcohn:musl
