### ISSUE TITLE
`set(CMAKE_OSX_ARCHITECTURES "i386;x86_64")` is too much of an assumption

### ISSUE THREAD

**Issue by raphaelcohn** [01org/IntelSEAPI#29]
set(CMAKE_OSX_ARCHITECTURES "i386;x86_64") assumes that the architectures being compiled for are `i386` and `x86_64`. 

This is too much of an assumption because it takes no account of the target architecture.

Additionally, this produces a 'fat' object archive, which is incompatible with third party tools and some language bindings (eg rust can not use 'fat' object archives). Arguably, that is a third party's problem, but it would be nice to either:-

* make this a compilation option;
* default to producing a 'thin' object archive for the current target architecture.

**Comment by araud** [comment]
Sure, I can guide you adding this option to buildall.py this will be an easy one.

**Comment by raphaelcohn** [comment]
Eh? That's what the point of cmake is. And the really nasty problem is this setting completely ignores the target architecture.
