### ISSUE TITLE
vs2013

### ISSUE THREAD

**Issue by dubik** [01org/IntelSEAPI#3]
Front page says: "on Windows requires Visual Studio 2013 and NSIS (http://nsis.sourceforge.net/) installed". When I tried to build master, buildall.py tried to use vs2012. Took a while to find "--vs" cmd option. I would mention that.

**Comment by araud** [comment]
Right, there was bug in VS detection. Could you please try with latest?

**Comment by dubik** [comment]
yes, it uses vs2013 by default now and works. Thanks for fixing.
Though I would mention --vs option. I had to check sources of buildall.py.
