### ISSUE TITLE
Static compilation is not supported

### ISSUE THREAD

**Issue by raphaelcohn** [01org/IntelSEAPI#30]
It is not possible to statically compile, eg TestIntelSEAPI, since it requires a dynamic library. If static compilation can never succeed for parts of the code base, then either warn or simple omit building them.

**Comment by araud** [comment]
Hello, Raphael!

I wonder how you run the build.
It is supposed to be buildall.py
And it has some options.

Please give me more information on the task you need to solve?

**Comment by raphaelcohn** [comment]
Fixed it for my local build by patching the CFLAGs hardcoded in the cmake files.

**Comment by raphaelcohn** [comment]
Note, also, the code in `jitprofiling.c` is making use of `dlclose()`. This function doesn't do anything in the musl c library, and its implementation is effectively broken in GNU libc, ie dynamic library unloading doesn't actually work. Sad but true.
