### ISSUE TITLE
PATH_MAX is not declared in <limits.h> on Fedora

### ISSUE THREAD

**Issue by heshuimu** [01org/IntelSEAPI#34]
OS: a private fork of Fedora

https://github.com/intel/IntelSEAPI/blob/6d743e1e4bb655a4f4987c69b23c2b39310cfd25/ittnotify/src/ittnotify/ittnotify_static.c#L269
https://github.com/intel/IntelSEAPI/blob/6d743e1e4bb655a4f4987c69b23c2b39310cfd25/ittnotify/src/ittnotify/ittnotify_static.c#L64

```
#cat /usr/include/linux/limits.h | grep PATH_MAX
#define PATH_MAX        4096	/* # chars in a path name including nul */
```

**Comment by araud** [comment]
please propose your pull request that fixes the issue for you
