### ISSUE TITLE
forgot to call __itt_id_create?

### ISSUE THREAD

**Issue by dubik** [01org/IntelSEAPI#4]
In few places in InstrumentationExample.cpp there is this kind of code:
```cpp
            id = __itt_id_make(&bOverlapped + counter++, 0);
            __itt_task_begin_overlapped(g_domain, id, __itt_null, handle_overlapped);
```

I believe it's missing `__itt_id_create(g_domain, id);`. Or is it?
[https://github.com/01org/IntelSEAPI/blob/master/InstrumentationExample.cpp#L174](https://github.com/01org/IntelSEAPI/blob/master/InstrumentationExample.cpp#L174)

**Comment by araud** [comment]
Sharp eye :)
But it's not mandatory when you're using ITT with IntelSEAPI, **__itt_id_make** is enough
