### ISSUE TITLE
Windows build/install don't copy the headers

### ISSUE THREAD

**Issue by cweiglemec** [01org/IntelSEAPI#6]
Downloaded source (clone repo, checkout master branch), built x86/x64 libraries, built installer, ran installer ... no headers in target directory.

Downloaded prebuilt windows installer from releases page, ran this installer instead, same problem.

Are the other platforms like this? Am I expected to copy the files around myself? Shouldn't the installers copy the headers?

**Comment by araud** [comment]
Thank you!
Please check in last update and let know if everything is fine?

With respect, Alex.

**Comment by cweiglemec** [comment]
I pulled and updated master. It looks like everything is in place now.
Thanks!

**Comment by araud** [comment]
Ah, great. Happy to hear that!
Thank you for reporting the issue.
Should you have any questions/ideas on the project, you can always contact me using email or Linked-in.
