### ISSUE TITLE
Cannot build it on macOS Sierra

### ISSUE THREAD

**Issue by enclle** [01org/IntelSEAPI#7]
Well, I can't if I just follow the manual.

I cloned IntelSEAPI, then in terminal I executed (as per manual):
python buildall.py -i
And it replied telling it cannot find cmake.

So I downloaded the CMake.dmg from www.cmake.org, installed it, and executed again:
python buildall.py -i

result was:

target_bits ['64']
Found JDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
/Users/.../IntelSEAPI
/Users/.../IntelSEAPI/build_darwin/64

>> cmake "/Users/.../IntelSEAPI" -G"Unix Makefiles"    -DJDK="/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home"
sh: cmake: command not found

>> make -j4
make: *** No targets specified and no makefile found.  Stop.

>> cpack "/Users/.../IntelSEAPI"
sh: cpack: command not found
Traceback (most recent call last):
  File "buildall.py", line 269, in <module>
    main()
  File "buildall.py", line 255, in main
    installer = glob.glob(os.path.join(work_folder, "IntelSEAPI*.sh"))[0]
IndexError: list index out of range

So, after some time I figured that cmake wasn't on the PATH, so I have to add:

export PATH=$PATH:/Applications/CMake.app/Contents/bin/

After that, I executed the command again, now with success:

python buildall.py -i

And it replied with:

[...]

clang: warning: -framework Cocoa: 'linker' input unused
1 warning generated.
1 warning generated.
[100%] Linking CXX shared library ../../bin/libIntelSEAPI.dylib
[100%] Built target sea_itt_lib

>> cpack "/Users/.../IntelSEAPI"
CPack: Create package using STGZ
CPack: Install projects
CPack: - Run preinstall target for: IntelSEAPI
CPack: - Install project: IntelSEAPI
CPack: Create package
CPack: - package: /Users/.../IntelSEAPI/build_darwin/64/IntelSEAPI-1.0.0-Darwin.sh generated.
/Users/.../IntelSEAPI/build_darwin/64/IntelSEAPI-1.0.0-Darwin.sh
======

Please, add a note to the manual telling that to run it on OS X/macOS you have to install the DMG from www.cmake.org and add the cmake bin to the PATH (export PATH=$PATH:/Applications/CMake.app/Contents/bin/).

Thank you.

**Comment by araud** [comment]
Thank you for detailed feedback!
I've updated the readme, please check if everything is fine and let me know, ok?

With respect, Alex.
